### ISSUE TITLE
Create model recognize text 

### ISSUE THREAD

**Issue by KittoDekiru1406** [KittoDekiru1406/card2file#1]
# Task Description:
- Integrate CRNN for character recognition according to the correct folder format
# Deadline
- Start Date: 2024-11-26
- Deadline: 2024-12-03
# Assignment
- Primary Responsible Person: @hung-manh @dovancuong12 
- Reviewer: @KittoDekiru1406

**Comment by dovancuong12** [comment]
@KittoDekiru1406 tôi với @hung-manh  đã tạo một PR cho Issue này nhé. 

Giờ tôi đóng cái này, nếu có vấn đề gì thì tạo một Issue khác nhé

**Comment by dovancuong12** [comment]
@KittoDekiru1406 tôi với @hung-manh đã tạo một PR cho Issue này nhé.

Giờ tôi đóng cái này, nếu có vấn đề gì thì tạo một Issue khác nhé

**Comment by dovancuong12** [comment]
@KittoDekiru1406 tôi với @hung-manh đã tạo một PR cho Issue này nhé.

Giờ tôi đóng cái này, nếu có vấn đề gì thì tạo một Issue khác nhé
