### ISSUE TITLE
Create Text Detection Model

### ISSUE THREAD

**Issue by KittoDekiru1406** [KittoDekiru1406/card2file#2]
# Task Description:
- Integrate CRAFT for character detection according to the correct folder format
# Deadline
- Start Date: 2024-11-26
- Deadline: 2024-12-03
# Assignment
- Primary Responsible Person: @KittoDekiru1406 
- Reviewer: @hung-manh @dovancuong12

**Comment by dovancuong12** [comment]
@KittoDekiru1406 Chưa close Issue như vậy là ông chưa hoàn thành DL nhé

**Comment by dovancuong12** [comment]
Để tôi đóng hộ ông nhé @KittoDekiru1406
