### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by KittoDekiru1406** [KittoDekiru1406/card2file#5]
# Task Description:
## Rotate image if it is skewed and config brightness
Deadline
Start Date: 2024-11-30
Deadline: 2024-12-05
Assignment
Primary Responsible Person: @KittoDekiru1406 
Reviewer: @hung-manh @dovancuong12

**Comment by dovancuong12** [comment]
@KittoDekiru1406 Tôi đợi ông, làm xong tạo một PR lên cho tôi Review
